### ISSUE TITLE
Boa Frente

### ISSUE THREAD

**Issue by giffel** [TrodsKey/Regnskovs-Project#76]

**Comment by p3ntaz** [comment]
indigenous people: http://www.sanandres.esc.edu.ar/olivosp/Extranet2001/5th/5B/Rainforest/Group4/People/people.htm

Janet, a girl who lives in the rainforests of Nicaragua https://msu.edu/user/urquhart/rainforest/Content/Rainforest-Girl.html

Befolkningens levevis: http://virtuelgalathea3.dk/artikel/naturbeskyttelse-og-b-redygtig-udvikling-af-regnskoven
