### ISSUE TITLE
Produktbeskrivelse

### ISSUE THREAD

**Issue by TrodsKey** [TrodsKey/Regnskovs-Project#89]

**Comment by TrodsKey** [comment]
https://docs.google.com/document/d/1W-OcG5cnWym5V5u9_xNzwlcAs23kQDxWewDNHAgTxWw/edit?usp=sharing

**Comment by p3ntaz** [comment]
https://docs.google.com/document/d/1kU9vDMy0hBko-XFkCiVmFdpku9nuwAnA0gPleAbWI-k/edit
